### PR TITLE
Fix gem warnings

### PR DESCRIPTION
**Pull request by andrewhavens**
This PR fixes an annoyance where warnings like this appear in the build log:

> Ignoring gem-1.2.3 because its extensions are not built

It is fixed by running `gen_bridge_metadata` in a clean Bundler environment so that Bundler doesn't print the warnings.

### CODE REVIEW

**Comment by digitalmoksha** [comment]
If this works, you. are. my. hero!

**Comment by digitalmoksha** [comment]
@andrewhavens I added in

```ruby
      defined?(Bundler) ? Bundler.with_clean_env { sh(cmd) } : sh(cmd)
```

to the `xcode_config.rb` to see if it worked - I'm still getting the wanrings

**Comment by andrewhavens** [comment]
Resolved conflicts. Ready to merge.

**Comment by andrewhavens** [comment]
@amirrajan Do you mind merging this?

**Comment by digitalmoksha** [comment]
@andrewhavens I pulled this change down, but I'm still getting the warnings:

```ruby
> rake clean
Ignoring byebug-11.1.1 because its extensions are not built. Try: gem pristine byebug --version 11.1.1
Ignoring byebug-11.0.1 because its extensions are not built. Try: gem pristine byebug --version 11.0.1
Ignoring byebug-9.0.6 because its extensions are not built. Try: gem pristine byebug --version 9.0.6
Ignoring commonmarker-0.17.9 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.9
Ignoring executable-hooks-1.6.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.0
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Ignoring jaro_winkler-1.5.4 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.4
Ignoring jaro_winkler-1.5.2 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.2
Ignoring json-2.3.0 because its extensions are not built. Try: gem pristine json --version 2.3.0
Ignoring json-2.2.0 because its extensions are not built. Try: gem pristine json --version 2.2.0
Ignoring redcarpet-3.4.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.4.0
Ignoring unf_ext-0.0.7.6 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.6
```

Am I missing something?

**Comment by andrewhavens** [comment]
@digitalmoksha There are multiple places in the RubyMotion codebase that need this fix, so there’s probably another place that needs it (and might not be open source.

**Comment by digitalmoksha** [comment]
@andrewhavens So I took a little closer look.  The one I'm seeing right now, which happens right at the beginning of running a rake task, is happening in `RubyMotion/lib/motion/project.rb` at line 46-49, where we check if there are any updates.  We're doing 

```ruby
  command = "/usr/bin/ruby \"#{motion_bin_path}\" update --check"
  defined?(Bundler) ? Bundler.with_clean_env { system(command) } : system(command)
```

I traced the requires in `motion`, and it's due to the `require 'yaml'` in `lib/motion/project/template.rb`.  Remove the require, and you no longer get the warnings.  But we do use YAML in that file, so the require might be necessary.

But I think the real fix is not running the update command with `/usr/bin/ruby`.  The `motion` binary is already set as an executable and begins with `#!/usr/bin/env ruby`.  So is there any reason to force it to run with the system ruby, rather than using the one specified by the environment?

**Pull request merged**
